version: "3.2"
services:
  iyuu:
    image: iyuu-plus-dev:latest
    build:
      context: ..
      dockerfile: Dockerfile # Dockerfile-CN for china user
    container_name: iyuu-plus-dev
    restart: always
    volumes:
      - ./logs:/iyuu/runtime/logs
    ports:
      - "8787:8787"
    depends_on:
      - db
    links:
      - db # 配置里面的数据库连接地址填 db 就行
  db:
    image: mariadb:11.3.2
    container_name: iyuu-plus-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD} # change it!!!!!!
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./db-data:/var/lib/mysql
